<script lang="ts">
  import { session } from "$lib/state";
  import { msToString, getNSolves, getAdjustedTime, dateToString } from "$lib/helpers";
  import DivideY from "./general/DivideY.svelte";
  import type { Solve, AoN } from "$lib/types";
  import ColoredTag from "./general/ColoredTag.svelte";

  let {
    index, // Index of this solve in current session solves array
    isPbSingle,
    isPbAo5,
    deleteSolve, // Callback to delete this solve
  }: {
    index: number,
    isPbSingle: boolean,
    isPbAo5: boolean,
    deleteSolve: () => void,
  } = $props();

  let singleCopied = $state(false);
  let ao5Copied = $state(false);
  let ao12Copied = $state(false);

  let solve = $derived($session.solves[index]);

  const getTimeString = () => {
    if (solve.timeMod === "None") {
      return msToString(solve.time);
    } else if (solve.timeMod === "+2") {
      return `${msToString(solve.time + 2000)} (${msToString(solve.time)} + 2)`;
    }
    return `DNF (${msToString(solve.time)})`;
  }

  // Gets N time objects for printing average of N info
  const getNTimes = (n: number) => {
    const nSolves = getNSolves($session.solves, index, n);
    if (!nSolves) {
      return {
        average: "",
        times: [],
      };
    }

    let minSoFar = Infinity;
    let minIndex = 0;
    let maxSoFar = -Infinity;
    let maxIndex = 0;

    for (let i = 0; i < n; i++) {
      const time = getAdjustedTime(nSolves[i]);
      if (time < minSoFar) {
        minSoFar = time;
        minIndex = i;
      }
      if (time > maxSoFar) {
        maxSoFar = time;
        maxIndex = i;
      }
    }

    let total = 0;
    for (let i = 0; i < n; i++) {
      if (i === minIndex || i === maxIndex) continue;
      total += getAdjustedTime(nSolves[i]);
    }

    return {
      average: msToString(total / (n - 2)),
      times: nSolves.map((x: Solve, i: number) => {
        const timeStr = msToString(getAdjustedTime(x));
        if (i === minIndex || i === maxIndex) {
          return {
            time: timeStr,
            outlier: true,
          };
        }
        return {
          time: timeStr,
          outlier: false,
        };
      }).reverse()
    };
  }

  let ao5Times = $derived<AoN>(getNTimes(5));
  let ao12Times = $derived<AoN>(getNTimes(12));

  const copySingleSummary = () => {
    let str = `Generated by MiniTimer on ${dateToString(Date.now())}`;
    if (solve.timeMod === "+2") {
      str += `\nSingle: ${msToString(solve.time + 2000)} (${msToString(solve.time)} + 2)`;
    } else if (solve.timeMod === "DNF") {
      str += `\nSingle: DNF (${msToString(solve.time)})`;
    } else {
      str += `\nSingle: ${msToString(solve.time)}`;
    }
    str += `\nScramble: ${solve.scramble.split('  ').join(' ')}`;
    navigator.clipboard.writeText(str);
  }

  const copyAo5Summary = () => {
    let str = `Generated by MiniTimer on ${dateToString(Date.now())}`;
    str += `\nAverage of 5: ${ao5Times.average}`;
    str += `\n\nTime list:`;
    for (let i = 0; i < 5; i++) {
      str += `\n${i + 1}. `;
      const timeMod = $session.solves[index + 4 - i].timeMod;
      if (ao5Times.times[i].outlier) {
        if (timeMod === "+2") {
          str += `(${ao5Times.times[i].time}+)`;
        } else if (timeMod === "DNF") {
          str += `(DNF)`;
        } else {
          str += `(${ao5Times.times[i].time})`;
        }
      } else {
        if (timeMod === "+2") {
          str += `${ao5Times.times[i].time}+`;
        } else if (timeMod === "DNF") {
          str += `DNF`;
        } else {
          str += `${ao5Times.times[i].time}`;
        }
      }
      str += ` --- ${$session.solves[index + i].scramble.split('  ').join(' ')}`;
    }
    navigator.clipboard.writeText(str);
  }

  const copyAo12Summary = () => {
    let str = `Generated by MiniTimer on ${dateToString(Date.now())}`;
    str += `\nAverage of 12: ${ao12Times.average}`;
    str += `\n\nTime list:`;
    for (let i = 0; i < 12; i++) {
      str += `\n${i + 1}. `;
      const timeMod = $session.solves[index + 11 - i].timeMod;
      if (ao12Times.times[i].outlier) {
        if (timeMod === "+2") {
          str += `(${ao12Times.times[i].time}+)`;
        } else if (timeMod === "DNF") {
          str += `(DNF)`;
        } else {
          str += `(${ao12Times.times[i].time})`;
        }
      } else {
        if (timeMod === "+2") {
          str += `${ao12Times.times[i].time}+`;
        } else if (timeMod === "DNF") {
          str += `DNF`;
        } else {
          str += `${ao12Times.times[i].time}`;
        }
      }
      str += ` --- ${$session.solves[index + i].scramble.split('  ').join(' ')}`;
    }
    navigator.clipboard.writeText(str);
  }
</script>

<div class="flex flex-wrap items-center gap-1">
  <h3 class="font-bold whitespace-nowrap mr-2">
    Solve {$session.solves.length - index}
  </h3>
  {#if isPbSingle}
    <ColoredTag
      color="bg-sky-500"
      textColor="text-white"
      text="PB Single"
    />
  {/if}
  {#if isPbAo5}
    <ColoredTag
      color="bg-sky-500"
      textColor="text-white"
      text="PB Ao5"
    />
  {/if}
</div>
<p class="text-xl mb-1 font-bold">
  {getTimeString()}
</p>
<p>
  {solve.scramble}
</p>
{#if solve.timestamp}
  <p class="text-sm">
    Solved on {dateToString(solve.timestamp)}
  </p>
{/if}

<DivideY />

<h4 class="text-sm font-bold">
  Average of 5
</h4>
<div class="flex gap-4">
  <p class="font-bold">
    {ao5Times.average ? `${ao5Times.average}:` : "N/A"}
  </p>
  <div class="flex flex-wrap gap-2">
    {#each ao5Times.times as ao5Time}
      <p>
        {#if ao5Time.outlier}
          ({ao5Time.time})
        {:else}
          {ao5Time.time}
        {/if}
      </p>
    {/each}
  </div>
</div>

<h4 class="text-sm font-bold mt-2">
  Average of 12
</h4>
<div class="flex gap-4">
  <p class="font-bold">
    {ao12Times.average ? `${ao12Times.average}:` : "N/A"}
  </p>
  <div class="flex flex-wrap gap-x-2">
    {#each ao12Times.times as ao12Time}
      <p>
        {#if ao12Time.outlier}
          ({ao12Time.time})
        {:else}
          {ao12Time.time}
        {/if}
      </p>
    {/each}
  </div>
</div>

<DivideY />

<div class="flex">
  <div class="grow flex flex-col">
    <h3 class="font-bold text-sm mb-1">
      Summary Texts
    </h3>
    <div class="flex gap-1">
      <button
        class="whitespace-nowrap font-bold text-sm min-w-20 px-2 py-1 bg-slate-100 hover:bg-amber-100 border border-black rounded-lg"
        onclick={() => {
          copySingleSummary();
          singleCopied = true;
          setTimeout(() => {
            singleCopied = false;
          }, 1000);
        }}
      >
        {singleCopied ? "Copied!" : "Single"}
      </button>
      <button
        class="whitespace-nowrap font-bold text-sm min-w-20 px-2 py-1 bg-slate-100 hover:bg-amber-100 border border-black rounded-lg"
        onclick={() => {
          copyAo5Summary();
          ao5Copied = true;
          setTimeout(() => {
            ao5Copied = false;
          }, 1000);
        }}
      >
        {ao5Copied ? "Copied!" : "Ao5"}
      </button>
      <button
        class="whitespace-nowrap font-bold text-sm min-w-20 px-2 py-1 bg-slate-100 hover:bg-amber-100 border border-black rounded-lg"
        onclick={() => {
          copyAo12Summary();
          ao12Copied = true;
          setTimeout(() => {
            ao12Copied = false;
          }, 1000);
        }}
      >
        {ao12Copied ? "Copied!" : "Ao12"}
      </button>
    </div>
  </div>

  <div class="flex items-end">
    <button
      class="whitespace-nowrap bg-red-500 h-min text-white font-bold text-sm px-2 py-1 rounded-lg"
      onclick={deleteSolve}
    >
      Delete
    </button>
  </div>
</div>
